import { useSelector, useDispatch }   from 'react-redux'
import { useState, useMemo }           from 'react'
import {
  ShoppingCart, Store, Building2, Trash2, Plus, Minus,
  Download, CheckCheck, X, ReceiptText, TrendingDown,
  ArrowDownToLine, Package, Leaf, Beef, Fish, Wheat,
  Egg, Apple, FlaskConical, ShoppingBasket, AlertCircle,
} from 'lucide-react'
import {
  selectShoppingItems, selectCheckedIds, selectShoppingTotals, selectShoppingCount,
  removeFromList, updateQty, setItemStore, toggleChecked, clearChecked, clearList,
} from '../app/store.js'
import { formatPrice, CATEGORY_ICONS }  from '../utils/helpers.js'
import { CategoryIcon }                 from '../components/commodity/CommodityCard.jsx'

// ─── Category color map ───────────────────────────────────────
const CAT_COLOR = {
  rice:'#0A3D2E', vegetables:'#166534', meat:'#7C2D12',
  fish:'#1E3A5F', fruits:'#713F12', eggs_dairy:'#1C1917', cooking:'#3B0764',
}

// ─── Download helpers ─────────────────────────────────────────
function buildTextContent(items, totals) {
  const line = '─'.repeat(48)
  const now  = new Date().toLocaleDateString('en-PH',{weekday:'long',year:'numeric',month:'long',day:'numeric'})
  const palengkeItems    = items.filter(i=>i.store==='palengke')
  const supermarketItems = items.filter(i=>i.store==='supermarket')

  let out = ''
  out += `PALENGKE WAIS — SHOPPING LIST\n`
  out += `Generated: ${now}\n`
  out += `${line}\n\n`

  if (palengkeItems.length) {
    out += `🏪  PALENGKE\n${line}\n`
    palengkeItems.forEach(i => {
      const price = formatPrice(i.palengke * i.qty)
      out += `  [ ]  ${i.name.padEnd(28)} x${i.qty} ${i.unit.padEnd(8)} ${price}\n`
    })
    const sub = palengkeItems.reduce((s,i)=>s+i.palengke*i.qty,0)
    out += `${''.padEnd(38)} ──────\n`
    out += `${'Palengke subtotal:'.padEnd(38)} ${formatPrice(sub)}\n\n`
  }

  if (supermarketItems.length) {
    out += `🏬  SUPERMARKET\n${line}\n`
    supermarketItems.forEach(i => {
      const price = formatPrice(i.supermarket * i.qty)
      out += `  [ ]  ${i.name.padEnd(28)} x${i.qty} ${i.unit.padEnd(8)} ${price}\n`
    })
    const sub = supermarketItems.reduce((s,i)=>s+i.supermarket*i.qty,0)
    out += `${''.padEnd(38)} ──────\n`
    out += `${'Supermarket subtotal:'.padEnd(38)} ${formatPrice(sub)}\n\n`
  }

  out += `${line}\n`
  out += `${'TOTAL ESTIMATED COST:'.padEnd(38)} ${formatPrice(totals.chosenTotal)}\n`
  out += `${'You save vs. buying all at SM:'.padEnd(38)} ${formatPrice(totals.savings)}\n`
  out += `\n* Prices from DA Price Monitoring (data.gov.ph) — May 2025\n`
  out += `* Generated by Palengke WAIS\n`
  return out
}

function downloadTxt(items, totals) {
  const content  = buildTextContent(items, totals)
  const blob     = new Blob([content], { type:'text/plain;charset=utf-8' })
  const url      = URL.createObjectURL(blob)
  const a        = document.createElement('a')
  a.href         = url
  a.download     = `palengke-wais-list-${Date.now()}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

function downloadCSV(items, totals) {
  const rows = [
    ['Store','Item','Category','Qty','Unit','Unit Price','Subtotal'],
    ...items.map(i => [
      i.store === 'palengke' ? 'Palengke' : 'Supermarket',
      i.name, i.category, i.qty, i.unit,
      i.store==='palengke' ? i.palengke : i.supermarket,
      (i.store==='palengke' ? i.palengke : i.supermarket) * i.qty,
    ]),
    [],
    ['','','','','','TOTAL:', totals.chosenTotal],
    ['','','','','','SAVINGS vs SM:', totals.savings],
  ]
  const csv  = rows.map(r=>r.join(',')).join('\n')
  const blob = new Blob([csv], { type:'text/csv;charset=utf-8' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `palengke-wais-list-${Date.now()}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Single row in the list ───────────────────────────────────
function ListRow({ item, checked }) {
  const dispatch   = useDispatch()
  const unitPrice  = item.store==='palengke' ? item.palengke : item.supermarket
  const subtotal   = unitPrice * item.qty
  const savings    = item.supermarket - item.palengke

  return (
    <div
      className={`sl-row ${checked ? 'sl-row-checked' : ''}`}
      style={{ animationDelay: '0ms' }}
    >
      {/* Checkbox */}
      <button
        className={`sl-check ${checked ? 'sl-check-done' : ''}`}
        onClick={() => dispatch(toggleChecked(item.id))}
        title="Mark as bought"
      >
        {checked && <CheckCheck size={14} />}
      </button>

      {/* Icon + Name */}
      <div className="sl-item-info">
        <div className="sl-item-icon" style={{ background: `${CAT_COLOR[item.category]}18`, border:`1px solid ${CAT_COLOR[item.category]}30` }}>
          <CategoryIcon category={item.category} size={16} color={CAT_COLOR[item.category] ?? '#0A3D2E'} />
        </div>
        <div>
          <p className="sl-item-name" style={{ textDecoration: checked ? 'line-through' : 'none', opacity: checked ? 0.45 : 1 }}>
            {item.name}
          </p>
          <p className="sl-item-unit">{item.unit}</p>
        </div>
      </div>

      {/* Store toggle */}
      <div className="sl-store-toggle">
        <button
          className={`sl-store-btn ${item.store==='palengke' ? 'active-green' : ''}`}
          onClick={() => dispatch(setItemStore({ id:item.id, store:'palengke' }))}
          title="Buy at Palengke"
        >
          <Store size={13} /> ₱{item.palengke}
        </button>
        <button
          className={`sl-store-btn ${item.store==='supermarket' ? 'active-blue' : ''}`}
          onClick={() => dispatch(setItemStore({ id:item.id, store:'supermarket' }))}
          title="Buy at Supermarket"
        >
          <Building2 size={13} /> ₱{item.supermarket}
        </button>
      </div>

      {/* Qty stepper */}
      <div className="sl-qty">
        <button className="sl-qty-btn" onClick={() => dispatch(updateQty({ id:item.id, qty:item.qty-1 }))}>
          <Minus size={12} />
        </button>
        <span className="sl-qty-val">{item.qty}</span>
        <button className="sl-qty-btn" onClick={() => dispatch(updateQty({ id:item.id, qty:item.qty+1 }))}>
          <Plus size={12} />
        </button>
      </div>

      {/* Subtotal */}
      <div className="sl-subtotal">
        <span className="sl-subtotal-val">{formatPrice(subtotal)}</span>
        {savings > 0 && item.store==='palengke' && (
          <span className="sl-subtotal-save">
            <TrendingDown size={10} /> save ₱{savings*item.qty}
          </span>
        )}
      </div>

      {/* Remove */}
      <button
        className="sl-remove"
        onClick={() => dispatch(removeFromList(item.id))}
        title="Remove"
      >
        <X size={15} />
      </button>
    </div>
  )
}

// ─── GROUP by store ───────────────────────────────────────────
function StoreSection({ title, icon: Icon, items, checkedIds, accentColor }) {
  if (!items.length) return null
  const subtotal = items.reduce((s,i)=>{
    const p = i.store==='palengke' ? i.palengke : i.supermarket
    return s + p*i.qty
  },0)

  return (
    <div className="sl-section">
      <div className="sl-section-header" style={{ borderColor: accentColor }}>
        <div className="sl-section-title" style={{ color: accentColor }}>
          <Icon size={16} />
          {title}
        </div>
        <span className="sl-section-sub">{items.length} item{items.length!==1?'s':''}</span>
        <span className="sl-section-total">Subtotal: <strong>{formatPrice(subtotal)}</strong></span>
      </div>
      <div className="sl-rows">
        {items.map(item => (
          <ListRow key={item.id} item={item} checked={checkedIds.includes(item.id)} />
        ))}
      </div>
    </div>
  )
}

// ─── MAIN PAGE ────────────────────────────────────────────────
export default function ShoppingListPage() {
  const dispatch     = useDispatch()
  const items        = useSelector(selectShoppingItems)
  const checkedIds   = useSelector(selectCheckedIds)
  const totals       = useSelector(selectShoppingTotals)
  const [showDownloadMenu, setShowDownloadMenu] = useState(false)

  const palengkeItems    = useMemo(() => items.filter(i=>i.store==='palengke'),    [items])
  const supermarketItems = useMemo(() => items.filter(i=>i.store==='supermarket'), [items])
  const checkedCount     = checkedIds.length

  if (items.length === 0) {
    return (
      <div className="page-in">
        {/* Page Hero */}
        <div className="sl-hero">
          <div className="container" style={{position:'relative',zIndex:1}}>
            <p className="section-label" style={{color:'var(--mint)'}}>
              <ShoppingCart size={13} style={{display:'inline',marginRight:4}} />
              Shopping List
            </p>
            <h1 className="sl-hero-title">Your Shopping List</h1>
            <p className="sl-hero-sub">Add items from the Prices page to build your smart list.</p>
          </div>
        </div>

        <div className="container" style={{padding:'4rem 2rem'}}>
          <div className="empty-state">
            <div className="empty-icon">
              <ShoppingCart size={32} color="var(--ink-3)" />
            </div>
            <h3 className="empty-title">Your list is empty</h3>
            <p className="empty-desc">
              Browse the Prices page and click <strong>"Add to List"</strong> on any commodity card to build your shopping list.
            </p>
            <a href="/prices" className="btn btn-primary" style={{marginTop:'0.5rem',textDecoration:'none'}}>
              <ShoppingBasket size={16} />
              Browse Prices
            </a>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="page-in">
      {/* ── Hero ── */}
      <div className="sl-hero">
        <div className="container" style={{position:'relative',zIndex:1}}>
          <div style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',flexWrap:'wrap',gap:'1rem'}}>
            <div>
              <p className="section-label" style={{color:'var(--mint)'}}>
                <ShoppingCart size={13} style={{display:'inline',marginRight:4}} />
                Shopping List
              </p>
              <h1 className="sl-hero-title">Your Shopping List</h1>
              <p className="sl-hero-sub">
                {items.length} item{items.length!==1?'s':''} ·
                {palengkeItems.length} at palengke ·
                {supermarketItems.length} at supermarket
              </p>
            </div>

            {/* Action buttons */}
            <div style={{display:'flex',gap:'0.6rem',flexWrap:'wrap',alignItems:'center'}}>
              {checkedCount > 0 && (
                <button className="btn btn-outline-inv btn-sm" onClick={() => dispatch(clearChecked())}>
                  <CheckCheck size={14} />
                  Remove Bought ({checkedCount})
                </button>
              )}
              <button className="btn btn-outline-inv btn-sm" onClick={() => dispatch(clearList())}>
                <Trash2 size={14} />
                Clear All
              </button>

              {/* Download dropdown */}
              <div style={{position:'relative'}}>
                <button
                  className="btn btn-primary btn-sm"
                  onClick={() => setShowDownloadMenu(v=>!v)}
                >
                  <Download size={14} />
                  Download List
                </button>
                {showDownloadMenu && (
                  <div className="sl-download-menu">
                    <button className="sl-download-opt" onClick={() => { downloadTxt(items,totals); setShowDownloadMenu(false) }}>
                      <ArrowDownToLine size={14} />
                      Download .txt
                    </button>
                    <button className="sl-download-opt" onClick={() => { downloadCSV(items,totals); setShowDownloadMenu(false) }}>
                      <ReceiptText size={14} />
                      Download .csv
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Summary pills */}
          <div className="sl-summary-pills">
            <div className="sl-pill">
              <span className="sl-pill-label">Total Estimate</span>
              <span className="sl-pill-value gold">{formatPrice(totals.chosenTotal)}</span>
            </div>
            <div className="sl-pill">
              <span className="sl-pill-label">If all at Palengke</span>
              <span className="sl-pill-value green">{formatPrice(totals.palengkeTotal)}</span>
            </div>
            <div className="sl-pill">
              <span className="sl-pill-label">If all at Supermarket</span>
              <span className="sl-pill-value muted">{formatPrice(totals.supermarketTotal)}</span>
            </div>
            {totals.savings > 0 && (
              <div className="sl-pill savings-glow">
                <span className="sl-pill-label">
                  <TrendingDown size={12} style={{display:'inline',marginRight:3}} />
                  You Save
                </span>
                <span className="sl-pill-value gold">{formatPrice(totals.savings)}</span>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ── List Body ── */}
      <div className="container" style={{padding:'2rem'}}>

        {/* Column headers */}
        <div className="sl-col-headers">
          <span style={{flex:'0 0 28px'}} />
          <span style={{flex:1}}>Item</span>
          <span style={{width:200,textAlign:'center'}}>Where to Buy</span>
          <span style={{width:110,textAlign:'center'}}>Quantity</span>
          <span style={{width:110,textAlign:'right'}}>Subtotal</span>
          <span style={{width:32}} />
        </div>

        {/* Palengke section */}
        <StoreSection
          title="Buy at Palengke"
          icon={Store}
          items={palengkeItems}
          checkedIds={checkedIds}
          accentColor="var(--forest-3)"
        />

        {/* Supermarket section */}
        <StoreSection
          title="Buy at Supermarket"
          icon={Building2}
          items={supermarketItems}
          checkedIds={checkedIds}
          accentColor="#3B82F6"
        />

        {/* Total breakdown card */}
        <div className="sl-total-card">
          <div className="sl-total-header">
            <ReceiptText size={18} color="var(--mint)" />
            <span>Estimated Total Breakdown</span>
          </div>
          <div className="sl-total-rows">
            {palengkeItems.length > 0 && (
              <div className="sl-total-row">
                <span className="sl-total-row-label">
                  <Store size={14} color="var(--forest-3)" />
                  Palengke subtotal ({palengkeItems.length} items)
                </span>
                <span className="sl-total-row-val green">
                  {formatPrice(palengkeItems.reduce((s,i)=>s+i.palengke*i.qty,0))}
                </span>
              </div>
            )}
            {supermarketItems.length > 0 && (
              <div className="sl-total-row">
                <span className="sl-total-row-label">
                  <Building2 size={14} color="#3B82F6" />
                  Supermarket subtotal ({supermarketItems.length} items)
                </span>
                <span className="sl-total-row-val blue">
                  {formatPrice(supermarketItems.reduce((s,i)=>s+i.supermarket*i.qty,0))}
                </span>
              </div>
            )}
            <div className="sl-total-divider" />
            <div className="sl-total-row grand">
              <span className="sl-total-row-label" style={{fontWeight:700,color:'var(--ink)'}}>
                TOTAL ESTIMATED COST
              </span>
              <span className="sl-total-row-val grand">{formatPrice(totals.chosenTotal)}</span>
            </div>
            {totals.savings > 0 && (
              <div className="sl-total-row" style={{background:'var(--gold-dim)',borderRadius:'var(--r-md)',padding:'0.75rem 1rem',marginTop:'0.5rem'}}>
                <span className="sl-total-row-label" style={{color:'#855A0A',fontWeight:600}}>
                  <TrendingDown size={14} color="#855A0A" />
                  Savings vs. buying everything at supermarket
                </span>
                <span className="sl-total-row-val" style={{color:'#855A0A',fontWeight:800,fontSize:'1.15rem'}}>
                  {formatPrice(totals.savings)}
                </span>
              </div>
            )}
          </div>
          <div className="sl-total-footer">
            <AlertCircle size={12} />
            Prices sourced from DA Price Monitoring (data.gov.ph) · Updated May 2025
          </div>
        </div>

        {/* Download CTA */}
        <div style={{display:'flex',gap:'0.75rem',justifyContent:'center',marginTop:'2rem',flexWrap:'wrap'}}>
          <button className="btn btn-dark btn-lg" onClick={() => downloadTxt(items,totals)}>
            <ArrowDownToLine size={16} />
            Download as .txt
          </button>
          <button className="btn btn-outline btn-lg" onClick={() => downloadCSV(items,totals)}>
            <ReceiptText size={16} />
            Download as .csv
          </button>
        </div>
      </div>
    </div>
  )
}
